<!-- Copyright (c) Files Community. Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release</Configurations>
		<Platforms>x64</Platforms>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

</Project>
